import '../models/animal.dart';

class AnimalRepository {
  static List<Animal> animals = [
    Animal(
      index: 0,
      name: "Aslan",
      imagePath: "assets/animal_images/lion.png",
      description: "merhaba ben bir aslanım",
    ),
    Animal(
      index: 1,
      name: "Fil",
      imagePath: "assets/animal_images/elephant.png",
      description: "merhaba ben bir filim",
    ),
    Animal(
      index: 2,
      name: "Kaplan",
      imagePath: "assets/animal_images/tiger.png",
      description: "merhaba ben bir kaplanım",
    ),
    Animal(
      index: 3,
      name: "Köpek",
      imagePath: "assets/animal_images/dog.png",
      description: "merhaba ben bir köpeğim",
    ),
    Animal(
      index: 4,
      name: "Kedi",
      imagePath: "assets/animal_images/cat.png",
      description: "merhaba ben bir kediyim",
    ),
    Animal(
      index: 5,
      name: "İnek",
      imagePath: "assets/animal_images/cow.png",
      description: "merhaba ben bir inek",
    ),
    Animal(
      index: 6,
      name: "At",
      imagePath: "assets/animal_images/horse.png",
      description: "merhaba ben bir atım",
    ),
    Animal(
      index: 7,
      name: "Horoz",
      imagePath: "assets/animal_images/rooster.png",
      description: "merhaba ben bir horozum",
    ),
    Animal(
      index: 8,
      name: "Ördek",
      imagePath: "assets/animal_images/duck.png",
      description: "merhaba ben bir ördeğim",
    ),
    Animal(
      index: 9,
      name: "Domuz",
      imagePath: "assets/animal_images/pig.png",
      description: "merhaba ben bir domuzum",
    ),
    Animal(
      index: 10,
      name: "Koyun",
      imagePath: "assets/animal_images/sheep.png",
      description: "merhaba ben bir koyunum",
    ),
    Animal(
      index: 11,
      name: "Maymun",
      imagePath: "assets/animal_images/monkey.png",
      description: "merhaba ben bir maymunum",
    ),
    Animal(
      index: 12,
      name: "Goril",
      imagePath: "assets/animal_images/gorilla.png",
      description: "merhaba ben bir gorilim",
    ),
    Animal(
      index: 13,
      name: "Penguen",
      imagePath: "assets/animal_images/penguin.png",
      description: "merhaba ben bir penguenim",
    ),
    Animal(
      index: 14,
      name: "Yunus",
      imagePath: "assets/animal_images/dolphin.png",
      description: "merhaba ben bir yunusum",
    ),
    Animal(
      index: 15,
      name: "Balina",
      imagePath: "assets/animal_images/whale.png",
      description: "merhaba ben bir balinayım",
    ),
    Animal(
      index: 16,
      name: "Zebra",
      imagePath: "assets/animal_images/zebra.png",
      description: "merhaba ben bir zebra",
    ),
    Animal(
      index: 17,
      name: "Zürafa",
      imagePath: "assets/animal_images/giraffe.png",
      description: "merhaba ben bir zürafa",
    ),
    Animal(
      index: 18,
      name: "Timsah",
      imagePath: "assets/animal_images/crocodile.png",
      description: "merhaba ben bir timsahım",
    ),
    Animal(
      index: 19,
      name: "Yılan",
      imagePath: "assets/animal_images/snake.png",
      description: "merhaba ben bir yılanım",
    ),
    Animal(
      index: 20,
      name: "Baykuş",
      imagePath: "assets/animal_images/owl.png",
      description: "merhaba ben bir baykuşum",
    ),
    Animal(
      index: 21,
      name: "Kurbağa",
      imagePath: "assets/animal_images/frog.png",
      description: "merhaba ben bir kurbağayım",
    ),
    Animal(
      index: 22,
      name: "Arı",
      imagePath: "assets/animal_images/bee.png",
      description: "merhaba ben bir arıyım",
    ),
    Animal(
      index: 23,
      name: "Ayı",
      imagePath: "assets/animal_images/bear.png",
      description: "merhaba ben bir ayıyım",
    ),
    Animal(
      index: 24,
      name: "Kurt",
      imagePath: "assets/animal_images/wolf.png",
      description: "merhaba ben bir kurtum",
    ),
    Animal(
      index: 25,
      name: "Koala",
      imagePath: "assets/animal_images/koala.png",
      description: "merhaba ben bir koalayım",
    ),
    Animal(
      index: 26,
      name: "Kanguru",
      imagePath: "assets/animal_images/kangaroo.png",
      description: "merhaba ben bir kanguruyum",
    ),
    Animal(
      index: 27,
      name: "Deve",
      imagePath: "assets/animal_images/camel.png",
      description: "merhaba ben bir deve",
    ),
    Animal(
      index: 28,
      name: "Çita",
      imagePath: "assets/animal_images/cheetah.png",
      description: "merhaba ben bir çitayım",
    ),
    Animal(
      index: 29,
      name: "Tilki",
      imagePath: "assets/animal_images/fox.png",
      description: "merhaba ben bir tilkiyim",
    ),
  ];
}
