import '../models/animal.dart';

class AnimalRepository {
  static List<Animal> animals = [
    Animal(
      index: 0,
      name: "lion",
      imagePath: "assets/animal_images/lion.png",
      soundPath: "assets/animal_sounds/lion.mp3",
      description: "merhaba ben bir aslanım",
    ),
    Animal(
      index: 1,
      name: "elephant",
      imagePath: "assets/animal_images/elephant.png",
      soundPath: "assets/animal_sounds/elephant.mp3",
      description: "merhaba ben bir filim",
    ),
    Animal(
      index: 2,
      name: "tiger",
      imagePath: "assets/animal_images/tiger.png",
      soundPath: "assets/animal_sounds/tiger.mp3",
      description: "merhaba ben bir kaplanım",
    ),
    Animal(
      index: 3,
      name: "dog",
      imagePath: "assets/animal_images/dog.png",
      soundPath: "assets/animal_sounds/dog.mp3",
      description: "merhaba ben bir köpeğim",
    ),
    Animal(
      index: 4,
      name: "cat",
      imagePath: "assets/animal_images/cat.png",
      soundPath: "assets/animal_sounds/cat.mp3",
      description: "merhaba ben bir kediyim",
    ),
    Animal(
      index: 5,
      name: "cow",
      imagePath: "assets/animal_images/cow.png",
      soundPath: "assets/animal_sounds/cow.mp3",
      description: "merhaba ben bir inek",
    ),
    Animal(
      index: 6,
      name: "horse",
      imagePath: "assets/animal_images/horse.png",
      soundPath: "assets/animal_sounds/horse.mp3",
      description: "merhaba ben bir atım",
    ),
    Animal(
      index: 7,
      name: "rooster",
      imagePath: "assets/animal_images/rooster.png",
      soundPath: "assets/animal_sounds/rooster.mp3",
      description: "merhaba ben bir horozum",
    ),
    Animal(
      index: 8,
      name: "duck",
      imagePath: "assets/animal_images/duck.png",
      soundPath: "assets/animal_sounds/duck.mp3",
      description: "merhaba ben bir ördeğim",
    ),
    Animal(
      index: 9,
      name: "pig",
      imagePath: "assets/animal_images/pig.png",
      soundPath: "assets/animal_sounds/pig.mp3",
      description: "merhaba ben bir domuzum",
    ),
    Animal(
      index: 10,
      name: "sheep",
      imagePath: "assets/animal_images/sheep.png",
      soundPath: "assets/animal_sounds/sheep.mp3",
      description: "merhaba ben bir koyunum",
    ),
    Animal(
      index: 11,
      name: "monkey",
      imagePath: "assets/animal_images/monkey.png",
      soundPath: "assets/animal_sounds/monkey.mp3",
      description: "merhaba ben bir maymunum",
    ),
    Animal(
      index: 12,
      name: "gorilla",
      imagePath: "assets/animal_images/gorilla.png",
      soundPath: "assets/animal_sounds/gorilla.mp3",
      description: "merhaba ben bir gorilim",
    ),
    Animal(
      index: 13,
      name: "penguin",
      imagePath: "assets/animal_images/penguin.png",
      soundPath: "assets/animal_sounds/penguin.mp3",
      description: "merhaba ben bir penguenim",
    ),
    Animal(
      index: 14,
      name: "dolphin",
      imagePath: "assets/animal_images/dolphin.png",
      soundPath: "assets/animal_sounds/dolphin.mp3",
      description: "merhaba ben bir yunusum",
    ),
    Animal(
      index: 15,
      name: "whale",
      imagePath: "assets/animal_images/whale.png",
      soundPath: "assets/animal_sounds/whale.mp3",
      description: "merhaba ben bir balinayım",
    ),
    Animal(
      index: 16,
      name: "zebra",
      imagePath: "assets/animal_images/zebra.png",
      soundPath: "assets/animal_sounds/zebra.mp3",
      description: "merhaba ben bir zebra",
    ),
    Animal(
      index: 17,
      name: "giraffe",
      imagePath: "assets/animal_images/giraffe.png",
      soundPath: "assets/animal_sounds/giraffe.mp3",
      description: "merhaba ben bir zürafa",
    ),
    Animal(
      index: 18,
      name: "crocodile",
      imagePath: "assets/animal_images/crocodile.png",
      soundPath: "assets/animal_sounds/crocodile.mp3",
      description: "merhaba ben bir timsahım",
    ),
    Animal(
      index: 19,
      name: "snake",
      imagePath: "assets/animal_images/snake.png",
      soundPath: "assets/animal_sounds/snake.mp3",
      description: "merhaba ben bir yılanım",
    ),
    Animal(
      index: 20,
      name: "owl",
      imagePath: "assets/animal_images/owl.png",
      soundPath: "assets/animal_sounds/owl.mp3",
      description: "merhaba ben bir baykuşum",
    ),
    Animal(
      index: 21,
      name: "frog",
      imagePath: "assets/animal_images/frog.png",
      soundPath: "assets/animal_sounds/frog.mp3",
      description: "merhaba ben bir kurbağayım",
    ),
    Animal(
      index: 22,
      name: "bee",
      imagePath: "assets/animal_images/bee.png",
      soundPath: "assets/animal_sounds/bee.mp3",
      description: "merhaba ben bir arıyım",
    ),
    Animal(
      index: 23,
      name: "bear",
      imagePath: "assets/animal_images/bear.png",
      soundPath: "assets/animal_sounds/bear.mp3",
      description: "merhaba ben bir ayıyım",
    ),
    Animal(
      index: 24,
      name: "wolf",
      imagePath: "assets/animal_images/wolf.png",
      soundPath: "assets/animal_sounds/wolf.mp3",
      description: "merhaba ben bir kurtum",
    ),
    Animal(
      index: 25,
      name: "koala",
      imagePath: "assets/animal_images/koala.png",
      soundPath: "assets/animal_sounds/koala.mp3",
      description: "merhaba ben bir koalayım",
    ),
    Animal(
      index: 26,
      name: "kangaroo",
      imagePath: "assets/animal_images/kangaroo.png",
      soundPath: "assets/animal_sounds/kangaroo.mp3",
      description: "merhaba ben bir kanguruyum",
    ),
    Animal(
      index: 27,
      name: "camel",
      imagePath: "assets/animal_images/camel.png",
      soundPath: "assets/animal_sounds/camel.mp3",
      description: "merhaba ben bir deve",
    ),
    Animal(
      index: 28,
      name: "cheetah",
      imagePath: "assets/animal_images/cheetah.png",
      soundPath: "assets/animal_sounds/cheetah.mp3",
      description: "merhaba ben bir çitayım",
    ),
    Animal(
      index: 29,
      name: "fox",
      imagePath: "assets/animal_images/fox.png",
      soundPath: "assets/animal_sounds/fox.mp3",
      description: "merhaba ben bir tilkiyim",
    ),
  ];
}
